### ISSUE TITLE
Feature request: forward packets between WiFi and Ethernet

### ISSUE THREAD

**Issue by buserp** [Puara/MPU#3]
Recently, I used the MPU in performance with three [T-Sticks](https://github.com/IDMIL/T-Stick/).

The three T-Sticks connected to the MPU via its WiFi hotspot, and the MPU connected to a laptop via ethernet. Our goal was to use the MPU as a WiFi hotspot that would forward packets to the laptop. Unfortunately, this is currently not possible, as the network interfaces on the MPU do not communicate with one another.

It would be useful to have packet forwarding be the default behavior, and this could most likely be achieved using a configuration like the one described here: https://superuser.com/questions/1715612/how-to-properly-forward-tcp-and-udp-traffic-between-interfaces-using-iptables.

**Comment by edumeneses** [comment]
Thanks for this issue

This is more of a (hidden) bug than a feature request. The SPU used to work like that, and somehow the config we used got broken after Raspberry Pi OS rebranding. I left it out of the [building instructions](https://github.com/Puara/MPU/blob/main/building_instructions_os.md) to avoid confusion, but I plan to get back to it when I have some time. Some [internet bridge tutorials online](https://www.elementzonline.com/blog/sharing-or-bridging-internet-to-ethernet-from-wifi-raspberry-pI) might be helpful.

If you hack the T-Tree into forwarding packages between interfaces, please let me know, and we can port the solution to the MPU. Otherwise, I'll try to get back on that after wrapping up the [NVIDIA Jetson MPU](https://gitlab.com/sat-mtl/distribution/jetson-images).

**Comment by edumeneses** [comment]
We are closing this issue here as we will migrate the OS part of the MPU to a different project. We will check traffic forwarding by then.
